#include "pch.h"
#include "Mapper.h"

#include <initializer_list>
#include <unordered_map>

static std::unordered_map<std::string, std::string> g_Mappings;

namespace {
	using Mappings = std::unordered_map<std::string, std::string>;

	Mappings CreateVanillaMappings()
	{
		return {
			{"net/minecraft/client/Minecraft", "net/minecraft/client/Minecraft"},
			{"net/minecraft/client/entity/AbstractClientPlayer", "net/minecraft/client/entity/AbstractClientPlayer"},
			{"net/minecraft/client/entity/EntityPlayerSP", "net/minecraft/client/entity/EntityPlayerSP"},
			{"net/minecraft/client/entity/EntityClientPlayerMP", "net/minecraft/client/entity/EntityPlayerSP"},
			{"net/minecraft/entity/EntityLivingBase", "net/minecraft/entity/EntityLivingBase"},
			{"net/minecraft/client/multiplayer/WorldClient", "net/minecraft/client/multiplayer/WorldClient"},
			{"net/minecraft/client/multiplayer/PlayerControllerMP", "net/minecraft/client/multiplayer/PlayerControllerMP"},
			{"net/minecraft/client/gui/GuiScreen", "net/minecraft/client/gui/GuiScreen"},
			{"net/minecraft/client/renderer/EntityRenderer", "net/minecraft/client/renderer/EntityRenderer"},
			{"net/minecraft/client/renderer/entity/RenderManager", "net/minecraft/client/renderer/entity/RenderManager"},
			{"net/minecraft/client/renderer/ActiveRenderInfo", "net/minecraft/client/renderer/ActiveRenderInfo"},
			{"net/minecraft/client/gui/inventory/GuiInventory", "net/minecraft/client/gui/inventory/GuiInventory"},
			{"net/minecraft/entity/Entity", "net/minecraft/entity/Entity"},
			{"net/minecraft/entity/player/EntityPlayer", "net/minecraft/entity/player/EntityPlayer"},
			{"net/minecraft/entity/item/EntityArmorStand", "net/minecraft/entity/item/EntityArmorStand"},
			{"net/minecraft/entity/item/EntityBoat", "net/minecraft/entity/item/EntityBoat"},
			{"net/minecraft/entity/item/EntityItem", "net/minecraft/entity/item/EntityItem"},
			{"net/minecraft/entity/item/EntityMinecart", "net/minecraft/entity/item/EntityMinecart"},
			{"net/minecraft/entity/item/EntityTNTPrimed", "net/minecraft/entity/item/EntityTNTPrimed"},
			{"net/minecraft/entity/item/EntityXPOrb", "net/minecraft/entity/item/EntityXPOrb"},
			{"net/minecraft/entity/monster/EntityMob", "net/minecraft/entity/monster/EntityMob"},
			{"net/minecraft/entity/passive/EntityAnimal", "net/minecraft/entity/passive/EntityAnimal"},
			{"net/minecraft/entity/projectile/EntityArrow", "net/minecraft/entity/projectile/EntityArrow"},
			{"net/minecraft/entity/projectile/EntityFireball", "net/minecraft/entity/projectile/EntityFireball"},
			{"net/minecraft/entity/player/InventoryPlayer", "net/minecraft/entity/player/InventoryPlayer"},
			{"net/minecraft/inventory/Container", "net/minecraft/inventory/Container"},
			{"net/minecraft/inventory/Slot", "net/minecraft/inventory/Slot"},
			{"net/minecraft/item/ItemStack", "net/minecraft/item/ItemStack"},
			{"net/minecraft/item/Item", "net/minecraft/item/Item"},
			{"net/minecraft/item/ItemArmor", "net/minecraft/item/ItemArmor"},
			{"net/minecraft/item/ItemFood", "net/minecraft/item/ItemFood"},
			{"net/minecraft/item/ItemAppleGold", "net/minecraft/item/ItemAppleGold"},
			{"net/minecraft/util/ResourceLocation", "net/minecraft/util/ResourceLocation"},
			{"net/minecraft/client/renderer/texture/TextureManager", "net/minecraft/client/renderer/texture/TextureManager"},
			{"net/minecraft/client/renderer/texture/ITextureObject", "net/minecraft/client/renderer/texture/ITextureObject"},
			{"net/minecraft/network/play/client/C16PacketClientStatus", "net/minecraft/network/play/client/C16PacketClientStatus"},
			{"net/minecraft/network/play/client/C16PacketClientStatus$EnumState", "net/minecraft/network/play/client/C16PacketClientStatus$EnumState"},
			{"net/minecraft/client/network/NetHandlerPlayClient", "net/minecraft/client/network/NetHandlerPlayClient"},
			{"net/minecraft/client/network/NetworkPlayerInfo", "net/minecraft/client/network/NetworkPlayerInfo"},
			{"net/minecraft/network/Packet", "net/minecraft/network/Packet"},
			{"net/minecraft/block/Block", "net/minecraft/block/Block"},
			{"net/minecraft/block/state/IBlockState", "net/minecraft/block/state/IBlockState"},
			{"net/minecraft/init/Blocks", "net/minecraft/init/Blocks"},
			{"net/minecraft/util/MovingObjectPosition", "net/minecraft/util/MovingObjectPosition"},
			{"net/minecraft/util/MovingObjectPosition$MovingObjectType", "net/minecraft/util/MovingObjectPosition$MovingObjectType"},
			{"net/minecraft/util/BlockPos", "net/minecraft/util/BlockPos"},
			{"net/minecraft/client/settings/GameSettings", "net/minecraft/client/settings/GameSettings"},
			{"net/minecraft/client/settings/KeyBinding", "net/minecraft/client/settings/KeyBinding"},
			{"net/minecraft/client/renderer/entity/Render", "net/minecraft/client/renderer/entity/Render"},
			{"net/minecraft/client/renderer/entity/RenderItem", "net/minecraft/client/renderer/entity/RenderItem"},
			{"net/minecraft/client/renderer/RenderHelper", "net/minecraft/client/renderer/RenderHelper"},
			{"net/minecraft/util/Timer", "net/minecraft/util/Timer"},
			{"net/minecraft/world/World", "net/minecraft/world/World"},
			{"net/minecraft/world/WorldSettings$GameType", "net/minecraft/world/WorldSettings$GameType"},
			{"net/minecraft/scoreboard/Scoreboard", "net/minecraft/scoreboard/Scoreboard"},
			{"net/minecraft/scoreboard/Team", "net/minecraft/scoreboard/Team"},
			{"net/minecraft/scoreboard/Team$EnumVisible", "net/minecraft/scoreboard/Team$EnumVisible"},
			{"net/minecraft/scoreboard/ScorePlayerTeam", "net/minecraft/scoreboard/ScorePlayerTeam"},
			{"net/minecraft/scoreboard/ScoreObjective", "net/minecraft/scoreboard/ScoreObjective"},
			{"net/minecraft/scoreboard/Score", "net/minecraft/scoreboard/Score"},
			{"net/minecraft/potion/Potion", "net/minecraft/potion/Potion"},
			{"net/minecraft/potion/PotionEffect", "net/minecraft/potion/PotionEffect"},
			{"net/minecraft/util/IChatComponent", "net/minecraft/util/IChatComponent"},
			{"net/minecraft/util/AxisAlignedBB", "net/minecraft/util/AxisAlignedBB"}
		};
	}

	void ApplyMappings(Mappings& mappings, const std::initializer_list<std::pair<const char*, const char*>>& entries)
	{
		for (const auto& entry : entries)
		{
			mappings[entry.first] = entry.second;
		}
	}

	void ApplyLunarMappings(Mappings& mappings)
	{
		ApplyMappings(mappings, {
			{"theMinecraft", "theMinecraft"},
			{"thePlayer", "thePlayer"},
			{"theWorld", "theWorld"},
			{"currentScreen", "currentScreen"},
			{"gameSettings", "gameSettings"},
			{"thirdPersonView", "thirdPersonView"},
			{"entityRenderer", "entityRenderer"},
			{"renderViewEntity", "renderViewEntity"},
			{"getRenderViewEntity", "getRenderViewEntity"},
			{"thirdPersonDistance", "thirdPersonDistance"},
			{"thirdPersonDistanceTemp", "thirdPersonDistanceTemp"},
			{"getFOVModifier", "getFOVModifier"},
			{"objectMouseOver", "objectMouseOver"},
			{"playerController", "playerController"},
			{"renderItem", "renderItem"},
			{"getRenderManager", "getRenderManager"},
			{"getEntityRenderObject", "getEntityRenderObject"},
			{"getNetHandler", "getNetHandler"},
			{"timer", "timer"},
			{"leftClickCounter", "leftClickCounter"},
			{"rightClickDelayTimer", "rightClickDelayTimer"},
			{"blockHitDelay", "blockHitDelay"},
			{"playerEntities", "playerEntities"},
			{"loadedEntityList", "loadedEntityList"},
			{"getMaxHealth", "getMaxHealth"},
			{"getHealth", "getHealth"},
			{"getTextureManager", "getTextureManager"},
			{"getBlockState", "getBlockState"},
			{"getBlock", "getBlock"},
			{"webBlock", "web"},
			{"getScoreboard", "getScoreboard"},
			{"getTeam", "getTeam"},
			{"getPlayersTeam", "getPlayersTeam"},
			{"createTeam", "createTeam"},
			{"addPlayerToTeam", "addPlayerToTeam"},
			{"removePlayerFromTeams", "removePlayerFromTeams"},
			{"removeTeam", "removeTeam"},
			{"getObjectiveInDisplaySlot", "getObjectiveInDisplaySlot"},
			{"getValueFromObjective", "getValueFromObjective"},
			{"getScorePoints", "getScorePoints"},
			{"getColorPrefix", "getColorPrefix"},
			{"getColorSuffix", "getColorSuffix"},
			{"getRegisteredName", "getRegisteredName"},
			{"getNameTagVisibility", "getNameTagVisibility"},
			{"setNameTagVisibility", "setNameTagVisibility"},
			{"getEnumVisibleByName", "byName"},
			{"isSameTeam", "isSameTeam"},
			{"PROJECTION", "PROJECTION"},
			{"MODELVIEW", "MODELVIEW"},
			{"getHeldItem", "getHeldItem"},
			{"isUsingItem", "isUsingItem"},
			{"getDisplayName", "getDisplayName"},
			{"getUnformattedTextForChat", "getUnformattedTextForChat"},
			{"getFormattedText", "getFormattedText"},
			{"getLocationSkin", "getLocationSkin"},
			{"getLocationSkinByName", "getLocationSkin"},
			{"bindTexture", "bindTexture"},
			{"getTexture", "getTexture"},
			{"getGlTextureId", "getGlTextureId"},
			{"getActivePotionEffect", "getActivePotionEffect"},
			{"jumpTicks", "jumpTicks"},
			{"rotationPitch", "rotationPitch"},
			{"rotationYaw", "rotationYaw"},
			{"prevRotationYaw", "prevRotationYaw"},
			{"prevRotationPitch", "prevRotationPitch"},
			{"posX", "posX"},
			{"posY", "posY"},
			{"posZ", "posZ"},
			{"lastTickPosX", "lastTickPosX"},
			{"lastTickPosY", "lastTickPosY"},
			{"lastTickPosZ", "lastTickPosZ"},
			{"motionX", "motionX"},
			{"motionY", "motionY"},
			{"motionZ", "motionZ"},
			{"isInWeb", "isInWeb"},
			{"onGround", "onGround"},
			{"hurtTime", "hurtTime"},
			{"hurtResistantTime", "hurtResistantTime"},
			{"maxHurtResistantTime", "maxHurtResistantTime"},
			{"swingProgressInt", "swingProgressInt"},
			{"getDistanceToEntity", "getDistanceToEntity"},
			{"getEyeHeight", "getEyeHeight"},
			{"isInvisible", "isInvisible"},
			{"setAlwaysRenderNameTag", "setAlwaysRenderNameTag"},
			{"setPosition", "setPosition"},
			{"renderDistanceWeight", "renderDistanceWeight"},
			{"getEntityBoundingBox", "getEntityBoundingBox"},
			{"typeOfHit", "typeOfHit"},
			{"BLOCK", "BLOCK"},
			{"ENTITY", "ENTITY"},
			{"entityHit", "entityHit"},
			{"getName", "getName"},
			{"getGameProfile", "getGameProfile"},
			{"inventory", "inventory"},
			{"inventoryContainer", "inventoryContainer"},
			{"currentItem", "currentItem"},
			{"keyBindUseItem", "keyBindUseItem"},
			{"setKeyBindState", "setKeyBindState"},
			{"displayGuiScreen", "displayGuiScreen"},
			{"onTick", "onTick"},
			{"keyCode", "keyCode"},
			{"windowClick", "windowClick"},
			{"windowId", "windowId"},
			{"getSlot", "getSlot"},
			{"getStack", "getStack"},
			{"item", "item"},
			{"metadata", "itemDamage"},
			{"getItem", "getItem"},
			{"getEntityItem", "getEntityItem"},
			{"getCurrentArmor", "getCurrentArmor"},
			{"getStackInSlot", "getStackInSlot"},
			{"getMaxDamage", "getMaxDamage"},
			{"getItemDamage", "getItemDamage"},
			{"armorType", "armorType"},
			{"damageReduceAmount", "damageReduceAmount"},
			{"sendUseItem", "sendUseItem"},
			{"sendQueue", "sendQueue"},
			{"addToSendQueue", "addToSendQueue"},
			{"getPlayerInfoMap", "getPlayerInfoMap"},
			{"getNetworkPlayerInfoGameProfile", "getGameProfile"},
			{"getNetworkPlayerInfoGameType", "getGameType"},
			{"getNetworkPlayerInfoPlayerTeam", "getPlayerTeam"},
			{"getGameTypeId", "getID"},
			{"updateController", "updateController"},
			{"renderItemIntoGUI", "renderItemIntoGUI"},
			{"doRender", "doRender"},
			{"enableGUIStandardItemLighting", "enableGUIStandardItemLighting"},
			{"disableStandardItemLighting", "disableStandardItemLighting"},
			{"regeneration", "regeneration"},
			{"potionTypes", "potionTypes"},
			{"duration", "duration"},
			{"getDuration", "getDuration"},
			{"setJumping", "setJumping"},
			{"width", "width"},
			{"height", "height"},
			{"renderPosX", "renderPosX"},
			{"renderPosY", "renderPosY"},
			{"renderPosZ", "renderPosZ"},
			{"renderPartialTicks", "renderPartialTicks"},
			{"boundingBox", "boundingBox"},
			{"minX", "minX"},
			{"minY", "minY"},
			{"minZ", "minZ"},
			{"maxX", "maxX"},
			{"maxY", "maxY"},
			{"maxZ", "maxZ"}
		});
	}

	void ApplySrgMappings(Mappings& mappings)
	{
		ApplyMappings(mappings, {
			{"theMinecraft", "field_71432_P"},
			{"thePlayer", "field_71439_g"},
			{"theWorld", "field_71441_e"},
			{"currentScreen", "field_71462_r"},
			{"gameSettings", "field_71474_y"},
			{"thirdPersonView", "field_74320_O"},
			{"entityRenderer", "field_71460_t"},
			{"renderViewEntity", "field_175622_Z"},
			{"getRenderViewEntity", "func_175606_aa"},
			{"thirdPersonDistance", "field_78490_B"},
			{"thirdPersonDistanceTemp", "field_78491_C"},
			{"getFOVModifier", "func_78481_a"},
			{"objectMouseOver", "field_71476_x"},
			{"playerController", "field_71442_b"},
			{"renderItem", "field_175621_X"},
			{"getRenderManager", "func_175598_ae"},
			{"getEntityRenderObject", "func_78713_a"},
			{"getNetHandler", "func_147114_u"},
			{"timer", "field_71428_T"},
			{"leftClickCounter", "field_71429_W"},
			{"rightClickDelayTimer", "field_71467_ac"},
			{"blockHitDelay", "field_78781_i"},
			{"playerEntities", "field_73010_i"},
			{"loadedEntityList", "field_72996_f"},
			{"getMaxHealth", "func_110138_aP"},
			{"getHealth", "func_110143_aJ"},
			{"getTextureManager", "func_110434_K"},
			{"getBlockState", "func_180495_p"},
			{"getBlock", "func_177230_c"},
			{"webBlock", "field_150321_G"},
			{"getScoreboard", "func_96441_U"},
			{"getTeam", "func_96508_e"},
			{"getPlayersTeam", "func_96509_i"},
			{"createTeam", "func_96527_f"},
			{"addPlayerToTeam", "func_151392_a"},
			{"removePlayerFromTeams", "func_96524_g"},
			{"removeTeam", "func_96511_d"},
			{"getObjectiveInDisplaySlot", "func_96539_a"},
			{"getValueFromObjective", "func_96529_a"},
			{"getScorePoints", "func_96652_c"},
			{"getColorPrefix", "func_96668_e"},
			{"getColorSuffix", "func_96663_f"},
			{"getRegisteredName", "func_96661_b"},
			{"getNameTagVisibility", "func_178770_i"},
			{"setNameTagVisibility", "func_178772_a"},
			{"getEnumVisibleByName", "func_178824_a"},
			{"isSameTeam", "func_142054_a"},
			{"PROJECTION", "field_178813_c"},
			{"MODELVIEW", "field_178812_b"},
			{"getHeldItem", "func_70694_bm"},
			{"isUsingItem", "func_71039_bw"},
			{"getDisplayName", "func_145748_c_"},
			{"getUnformattedTextForChat", "func_150261_e"},
			{"getFormattedText", "func_150254_d"},
			{"getLocationSkin", "func_110306_p"},
			{"getLocationSkinByName", "func_110311_f"},
			{"bindTexture", "func_110577_a"},
			{"getTexture", "func_110581_b"},
			{"getGlTextureId", "func_110552_b"},
			{"getActivePotionEffect", "func_70660_b"},
			{"jumpTicks", "field_70773_bE"},
			{"rotationPitch", "field_70125_A"},
			{"rotationYaw", "field_70177_z"},
			{"prevRotationYaw", "field_70126_B"},
			{"prevRotationPitch", "field_70127_C"},
			{"posX", "field_70165_t"},
			{"posY", "field_70163_u"},
			{"posZ", "field_70161_v"},
			{"lastTickPosX", "field_70142_S"},
			{"lastTickPosY", "field_70137_T"},
			{"lastTickPosZ", "field_70136_U"},
			{"motionX", "field_70159_w"},
			{"motionY", "field_70181_x"},
			{"motionZ", "field_70179_y"},
			{"isInWeb", "field_70134_J"},
			{"onGround", "field_70122_E"},
			{"hurtTime", "field_70737_aN"},
			{"hurtResistantTime", "field_70172_ad"},
			{"maxHurtResistantTime", "field_70771_an"},
			{"swingProgressInt", "field_110158_av"},
			{"getDistanceToEntity", "func_70032_d"},
			{"getEyeHeight", "func_70047_e"},
			{"isInvisible", "func_82150_aj"},
			{"setAlwaysRenderNameTag", "func_174805_g"},
			{"setPosition", "func_70107_b"},
			{"renderDistanceWeight", "field_70155_l"},
			{"getEntityBoundingBox", "func_174813_aQ"},
			{"typeOfHit", "field_72313_a"},
			{"BLOCK", "BLOCK"},
			{"ENTITY", "ENTITY"},
			{"entityHit", "field_72308_g"},
			{"getName", "func_70005_c_"},
			{"getGameProfile", "func_146103_bH"},
			{"inventory", "field_71071_by"},
			{"inventoryContainer", "field_71069_bz"},
			{"currentItem", "field_70461_c"},
			{"keyBindUseItem", "field_74313_G"},
			{"setKeyBindState", "func_74510_a"},
			{"displayGuiScreen", "func_147108_a"},
			{"onTick", "func_74507_a"},
			{"keyCode", "field_74512_d"},
			{"windowClick", "func_78753_a"},
			{"windowId", "field_75152_c"},
			{"getSlot", "func_75139_a"},
			{"getStack", "func_75211_c"},
			{"item", "field_151002_e"},
			{"metadata", "field_77991_e"},
			{"getItem", "func_77973_b"},
			{"getEntityItem", "func_92059_d"},
			{"getCurrentArmor", "func_82169_q"},
			{"getStackInSlot", "func_70301_a"},
			{"getMaxDamage", "func_77958_k"},
			{"getItemDamage", "func_77952_i"},
			{"armorType", "field_77881_a"},
			{"damageReduceAmount", "field_77879_b"},
			{"sendUseItem", "func_78769_a"},
			{"sendQueue", "field_71174_a"},
			{"addToSendQueue", "func_147297_a"},
			{"getPlayerInfoMap", "func_175106_d"},
			{"getNetworkPlayerInfoGameProfile", "func_178845_a"},
			{"getNetworkPlayerInfoGameType", "func_178848_b"},
			{"getNetworkPlayerInfoPlayerTeam", "func_178850_i"},
			{"getGameTypeId", "func_77148_a"},
			{"updateController", "func_78765_e"},
			{"renderItemIntoGUI", "func_175042_a"},
			{"doRender", "func_76986_a"},
			{"enableGUIStandardItemLighting", "func_74520_c"},
			{"disableStandardItemLighting", "func_74518_a"},
			{"regeneration", "field_76428_l"},
			{"potionTypes", "field_76425_a"},
			{"duration", "field_76460_b"},
			{"getDuration", "func_76459_b"},
			{"setJumping", "func_70637_d"},
			{"width", "field_70130_N"},
			{"height", "field_70131_O"},
			{"renderPosX", "field_78725_b"},
			{"renderPosY", "field_78726_c"},
			{"renderPosZ", "field_78723_d"},
			{"renderPartialTicks", "field_74281_c"},
			{"boundingBox", "field_70121_D"},
			{"minX", "field_72340_a"},
			{"minY", "field_72338_b"},
			{"minZ", "field_72339_c"},
			{"maxX", "field_72336_d"},
			{"maxY", "field_72337_e"},
			{"maxZ", "field_72334_f"}
		});
	}
}

void Mapper::Initialize(const GameVersions version)
{
	g_Mappings.clear();

	switch (version)
	{
	case BADLION: {
		g_Mappings = {
			{"net/minecraft/client/Minecraft", "ave"},
			{"net/minecraft/client/entity/AbstractClientPlayer", "bet"},
			{"net/minecraft/client/entity/EntityClientPlayerMP", "bew"},
			{"net/minecraft/client/entity/EntityPlayerSP", "bew"},
			{"net/minecraft/entity/EntityLivingBase", "pr"},
			{"net/minecraft/client/multiplayer/WorldClient", "bdb"},
			{"net/minecraft/client/multiplayer/PlayerControllerMP", "bda"},
			{"sendUseItem", "a"},
			{"attackEntity", "a"},
			{"net/minecraft/client/gui/GuiScreen", "axu"},
			{"net/minecraft/client/renderer/EntityRenderer", "bfk"},
			{"net/minecraft/client/renderer/entity/RenderManager", "biu"},
			{ "net/minecraft/entity/Entity", "pk" },
			{"net/minecraft/client/renderer/entity/Render", "biv"},
				{"net/minecraft/inventory/Container", "xi"},
			{"net/minecraft/client/model/ModelBase", "bbo"},
			{"net/minecraft/client/renderer/ActiveRenderInfo", "auz"},
			{ "net/minecraft/util/IChatComponent", "eu" },
			{"net/minecraft/client/model/ModelRenderer", "bct"},
			{"net/minecraft/util/Timer", "avl"},
			{"net/minecraft/client/gui/Gui", "avp"},
			{"net/minecraft/client/gui/FontRenderer", "avn"},
			{"net/minecraft/util/AxisAlignedBB", "aug"},
			{"net/minecraft/client/gui/GuiChat", "awv"},
			{"net/minecraft/client/renderer/entity/RendererLivingEntity", "bjl"},
			{"net/minecraft/item/ItemStack", "zx"},
			{"net/minecraft/item/ItemSword", "aay"},
			{"net/minecraft/item/ItemAxe", "yl"},
			{"net/minecraft/item/Item", "zw"},
			{"net/minecraft/block/Block", "afh"},
			{"net/minecraft/block/state/IBlockState", "alz"},
			{"net/minecraft/init/Blocks", "ajn"},
			{ "net/minecraft/item/ItemBlock", "yo" },
			{"net/minecraft/util/MovingObjectPosition$MovingObjectType", "auh$a"},
			{"net/minecraft/util/MovingObjectPosition", "auh"},
			{"net/minecraft/util/BlockPos", "cj"},
			{"net/minecraft/client/gui/inventory/GuiInventory", "azc"},
			{"net/minecraft/client/gui/GuiChat", "awv"},
			{"net/minecraft/entity/player/InventoryPlayer", "wm"},
			{"net/minecraft/item/ItemEnderPearl", "zk"},
			{"net/minecraft/client/renderer/entity/RenderEntityItem", "bjf"},
			{"net/minecraft/entity/item/EntityItem", "uz"},
			{"net/minecraft/entity/item/EntityArmorStand", "um"},
			{"net/minecraft/entity/item/EntityBoat", "ux"},
			{"net/minecraft/entity/item/EntityMinecart", "va"},
			{"net/minecraft/entity/item/EntityTNTPrimed", "vj"},
			{"net/minecraft/entity/item/EntityXPOrb", "pp"},
			{"net/minecraft/entity/monster/EntityMob", "vv"},
			{"net/minecraft/entity/passive/EntityAnimal", "tm"},
			{"net/minecraft/entity/projectile/EntityArrow", "wq"},
			{"net/minecraft/entity/projectile/EntityFireball", "ws"},
			{"net/minecraft/client/settings/GameSettings", "avh"},
			{ "net/minecraft/client/settings/KeyBinding", "avb" },
			{ "keyBindSprint", "ae" },
			{ "pressed", "h" },
			{ "pressTime", "i" },
			{"gameSettings", "t"},
			{"thirdPersonView", "aB"},
			{"entityRenderer", "o"},
			{"renderViewEntity", "ad"},
			{"getRenderViewEntity", "ac"},
			{"thirdPersonDistance", "q"},
			{"thirdPersonDistanceTemp", "r"},
			{"getFOVModifier", "a"},
			{"getTextureManager", "P"},
			{"getBlockState", "p"},
			{ "getBlock", "c" },
			{"webBlock", "G"},
			{ "loadedEntityList", "f" },
			{"theMinecraft", "S"},
			{"thePlayer", "h"},
			{"theWorld", "f"},
			{"currentScreen", "m"},
			{"getNetHandler", "u"},
			{"getRenderManager", "af"},
			{"getEntityRenderObject", "a"},
			{"doRenderEntity", "a"},
			{"mainModel", "f"},
			{"PROJECTION", "c"},
			{"MODELVIEW", "b"},
			{"getSlot", "a"},
			{"playerEntities", "j"},
			{"renderDistanceWeight", "j"},
			{"getEntityBoundingBox", "aR"},
			{ "getDisplayName", "f_" },
			{"getUnformattedTextForChat", "e"},
			{"getFormattedText", "d"},
			{"getLocationSkin", "i"},
			{"getLocationSkinByName", "c"},
			{"rotationPitch", "z"},
			{ "jumpTicks", "bn" },
			{"rotationYaw", "y"},
			{"prevRotationYaw", "A"},
			{"prevRotationPitch", "B"},
			{"posX", "s"},
			{"posY", "t"},
			{"posZ", "u"},
			{"motionX", "v"},
			{"motionY", "w"},
			{"motionZ", "x"},
			{"maxHurtResistantTime", "aD"},
			{"hurtResistantTime", "Z"},
			{"hurtTime", "au"},
			{"bipedHeadwear", "f"},
			{"bipedRightArm", "h"},
			{"bipedLeftArm", "i"},
			{"bipedRightLeg", "j"},
			{"bipedLeftLeg", "k"},
			{"rotateAngleX","f"},
			{"rotateAngleY","g"},
			{"rotateAngleZ","h"},
			{"prevRenderYawOffset", "aJ"},
			{"renderYawOffset", "aI"},
			{"renderPartialTicks", "c"},
			{"lastTickPosX", "P"},
			{"lastTickPosY", "Q"},
			{"lastTickPosZ", "R"},
			{"timer", "Y"},
			{"net/minecraft/util/MovementInput", "beu"},
			{"movementInput", "b"},
			{"moveStrafeInput", "a"},
			{"moveForwardInput", "b"},
			{"jumpInput", "c"},
			{"sneakInput", "d"},
			{"keyBindForward", "Y"},
			{"keyBindBack", "aa"},
			{"keyBindLeft", "Z"},
			{"keyBindRight", "ab"},
			{"keyBindJump", "ac"},
			{"keyBindSprint", "ae"},
			{"keyBindSneak", "ad"},
			{"getDistanceToEntity", "g"},
			{"getEyeHeight", "aS"},
			{"regeneration", "l"},
			{"isUsingItem", "bS"},
			{"swingItem", "bw"},
			{"getActivePotionEffect", "b"},
			{"potionID", "b"},
			{"getPotionID", "a"},
			{"getDuration", "b"},
			{"duration", "c"},
			{"potionId", "l"},
			{"getEntityItem", "l"},
			{"itemRenderer", "a"},
			{"doRender", "a"},
			{"displayWidth", "d"},
			{"displayHeight", "e"},
			{ "renderPosX", "o" },
			{ "renderPosY", "p" },
			{ "renderPosZ", "q" },
			{"drawRect", "a"},
			{"getStringWidth", "a"},
			{"drawString", "a"},
			{"fontRendererObj", "k"},
			{ "getHealth", "bn" },
			{ "getMaxHealth", "bu" },
			{"setAlwaysRenderNameTag",  "g"},
			{ "setInvisible", "e" },
			{ "isInvisible", "ax" },
			{"maxHurtResistantTime", "aD"},
			{"hurtResistantTime", "Z"},
			{ "viewerPosX", "h" },
			{ "viewerPosY", "i" },
			{ "viewerPosZ", "j" },
			{"boundingBox", "f"},
			{"minX", "a"},
			{"minY", "b"},
			{"minZ", "c"},
			{"maxX", "d"},
			{"maxY", "e"},
			{"maxZ", "f"},
			{"prevPosX", "p"},
			{"prevPosY", "q"},
			{"prevPosZ", "r"},
			{"isSneaking", "av"},
			{ "isSprinting", "aw" },
			{ "setSprinting", "d" },
			{"rotationYawHead", "aK"},
			{"onGround", "C"},
			{"getHeldItem", "bA"},
			{"item", "d"},
			{"getItem", "b"},
			{"typeOfHit", "a"},
			{"BLOCK", "b"},
			{"ENTITY", "c"},
			{ "objectMouseOver", "s" },
			{ "inWater", "Y" },
			{ "isInWeb", "H" },
			{ "moveForwardEntity", "ba" },
			{ "moveStrafingEntity", "aZ" },
			{ "timerSpeed", "d" },
			{ "inventory", "bi" },
			{ "currentItem", "c" },
			{ "getStackInSlot", "a" },
			{ "getStackDisplayName", "q" },
			{ "metadata", "f" },
			{"entityHit", "d"},
			{"getName", "e_"},
			{"getGameProfile", "cd"},
			{"getDisplayName", "f_"},
			{"getFormattedText", "d"},
			{ "getDebugFPS", "ai"},
			{"setPosition", "b"},
			{"leftClickCounter", "ag"},
			{ "hurtResistantTime", "Z" },
			{ "isSwingInProgress", "ar" },
			{ "getCurrentArmor", "q" },
			{ "getMaxDamage", "j" },
			{ "getItemDamage", "h" },
			{ "dropOneItem", "a" },
			{ "keyBindUseItem", "ag" },
			{ "slotIn", "p_82169_1_" },
			{ "slotIn", "I" },
			{ "rightClickDelayTimer", "ap" },
			{ "blockHitDelay", "g" },
			{ "keyBindAttack", "ai" },
			{ "setKeyBindState", "a" },
			{ "onTick", "a" },
			{ "keyCode", "g" },
			{ "width", "J" },
			{ "height", "K" },
			{ "net/minecraft/scoreboard/Scoreboard", "auo" },
			{ "net/minecraft/scoreboard/Team", "auq" },
			{ "net/minecraft/scoreboard/Team$EnumVisible", "auq$a" },
			{ "net/minecraft/scoreboard/ScorePlayerTeam", "aul" },
			{"net/minecraft/util/ResourceLocation", "jy"},
			{"net/minecraft/client/renderer/texture/TextureManager", "bmj"},
			{"net/minecraft/client/renderer/texture/ITextureObject", "bmk"},
			{"bindTexture", "a"},
			{"getTexture", "b"},
			{"getGlTextureId", "b"},
			{ "net/minecraft/client/renderer/entity/RenderItem", "bjh" },
			{ "net/minecraft/client/renderer/RenderHelper", "avc" },
			{ "getScoreboard", "Z" },
			{ "getTeam", "d" },
			{ "getPlayersTeam", "h" },
			{ "createTeam", "e" },
			{ "addPlayerToTeam", "a" },
			{ "removePlayerFromTeams", "f" },
			{ "removeTeam", "d" },
			{ "getColorPrefix", "e" },
			{ "getColorSuffix", "f" },
			{ "getRegisteredName", "b" },
			{ "getNameTagVisibility", "i" },
			{ "setNameTagVisibility", "a" },
			{ "getEnumVisibleByName", "a" },
			{ "isSameTeam", "a" },
			{ "renderItem", "ab" },
			{ "renderItemIntoGUI", "a" },
			{ "enableGUIStandardItemLighting", "c" },
			{ "disableStandardItemLighting", "a" },
			{ "net/minecraft/entity/player/EntityPlayer", "wn" },
			{ "net/minecraft/world/World", "adm" },
			{ "net/minecraft/client/multiplayer/WorldClient", "bdb" },
			{ "net/minecraft/scoreboard/ScoreObjective", "auk" },
			{ "net/minecraft/scoreboard/Score", "aum" },
			{ "getObjectiveInDisplaySlot", "a" },
			{ "getObjective", "b" },
			{ "getValueFromObjective", "c" },
			{ "getScorePoints", "c" },
			{ "getAbsorptionAmount", "bN" },
			{ "swingItem", "bw" },
			{ "clickMouse", "aw" },
			{ "swingProgressInt", "as" },
			{ "playerController", "c" },
			{ "windowClick", "a" },
			{ "inventoryContainer", "bj" },
			{ "windowId", "d" },
			{ "net/minecraft/item/ItemArmor", "yj" },
			{ "net/minecraft/item/ItemFood", "zs" },
			{ "net/minecraft/item/ItemAppleGold", "zt" },
			{ "net/minecraft/item/ItemEnderPearl", "zk" },
			{ "net/minecraft/potion/Potion", "pe" },
			{ "net/minecraft/potion/PotionEffect", "pf" },
			{ "potionTypes", "a" },
			{ "net/minecraft/entity/item/EntityItem", "uz" },
			{ "net/minecraft/client/renderer/entity/RenderEntityItem", "bjf" },
			{ "net/minecraft/inventory/Container", "xi" },
			{ "net/minecraft/inventory/Slot", "yg" },
			{ "getSlot", "a" },
			{ "getStack", "d" },
			{ "getMaxDamage", "j" },
			{ "getItemDamage", "h" },
			{ "armorType", "b" },
			{ "damageReduceAmount", "c" },
			{ "displayGuiScreen", "a" },
			{ "closeScreen", "n" },
			{ "updateController", "e" },
			{ "net/minecraft/network/play/client/C16PacketClientStatus", "ig" },
			{ "net/minecraft/network/play/client/C16PacketClientStatus$EnumState", "ig$a" },
			{ "OPEN_INVENTORY_ACHIEVEMENT", "c" },
			{ "PERFORM_RESPAWN", "a" },
			{ "net/minecraft/network/play/client/C0BPacketEntityAction", "is" },
			{ "net/minecraft/network/play/client/C0BPacketEntityAction$Action", "is$a" },
			{ "START_SPRINTING", "d" },
			{ "STOP_SPRINTING", "e" },
			{ "sendQueue", "a" },
			{ "addToSendQueue", "a" },
			{ "getPlayerInfoMap", "d" },
			{ "getNetworkPlayerInfoGameProfile", "a" },
			{ "getNetworkPlayerInfoGameType", "b" },
			{ "getNetworkPlayerInfoPlayerTeam", "i" },
			{ "getGameTypeId", "a" },
			{ "net/minecraft/client/network/NetHandlerPlayClient", "bcy" },
			{ "net/minecraft/client/network/NetworkPlayerInfo", "bdc" },
			{ "net/minecraft/world/WorldSettings$GameType", "adp$a" },
			{ "net/minecraft/network/Packet", "ff" },
			{ "net/minecraft/network/play/client/C03PacketPlayer", "ip" },
			{ "net/minecraft/network/play/client/C03PacketPlayer$C05PacketPlayerLook", "ip$c" },
			{ "yaw", "d" },
			{ "pitch", "e" },
			{ "rotating", "h" }
		};
		break;
	}
	case FORGE_1_8:
	case FEATHER_1_8: {
		g_Mappings = CreateVanillaMappings();
		ApplySrgMappings(g_Mappings);
		break;
	}
	case LUNAR: {
		g_Mappings = CreateVanillaMappings();
		ApplyLunarMappings(g_Mappings);
		break;
	}
	default:
		break;
	}
}

std::string Mapper::Get(const char* mapping, int type)
{
	auto it = g_Mappings.find(mapping);
	if (it == g_Mappings.end())
		return std::string("");

	std::string ret;
	switch (type)
	{
	case 1:
		ret = it->second;
		break;
	case 2:
		ret = "L" + it->second + ";";
		break;
	case 3:
		ret = "()L" + it->second + ";";
		break;
	default:
		ret = it->second;
		break;
	}

	return ret;
}
