#include "pch.h"
#include "Mapper.h"

#include <unordered_map>

static std::unordered_map<std::string, std::string> g_Mappings;

void Mapper::Initialize(const GameVersions version)
{
	switch (version)
	{
	case CASUAL_1_8: {
		g_Mappings = {
			{"net/minecraft/client/Minecraft", "ave"},
			{"net/minecraft/client/entity/AbstractClientPlayer", "bet"},
			{"net/minecraft/client/entity/EntityClientPlayerMP", "bew"},
			{"net/minecraft/client/entity/EntityPlayerSP", "bew"},
			{"net/minecraft/entity/EntityLivingBase", "pr"},
			{"net/minecraft/client/multiplayer/WorldClient", "bdb"},
			{"net/minecraft/client/multiplayer/PlayerControllerMP", "bda"},
			{"sendUseItem", "a"},
			{"attackEntity", "a"},
			{"net/minecraft/client/gui/GuiScreen", "axu"},
			{"net/minecraft/client/renderer/entity/RenderManager", "biu"},
			{ "net/minecraft/entity/Entity", "pk" },
			{"net/minecraft/client/renderer/entity/Render", "biv"},
				{"net/minecraft/inventory/Container", "xi"},
			{"net/minecraft/client/model/ModelBase", "bbo"},
			{"net/minecraft/client/renderer/ActiveRenderInfo", "auz"},
			{ "net/minecraft/util/IChatComponent", "eu" },
			{"net/minecraft/client/model/ModelRenderer", "bct"},
			{"net/minecraft/util/Timer", "avl"},
			{"net/minecraft/client/gui/Gui", "avp"},
			{"net/minecraft/client/gui/FontRenderer", "avn"},
			{"net/minecraft/util/AxisAlignedBB", "aug"},
			{"net/minecraft/client/gui/GuiChat", "awv"},
			{"net/minecraft/client/renderer/entity/RendererLivingEntity", "bjl"},
			{"net/minecraft/item/ItemStack", "zx"},
			{"net/minecraft/item/ItemSword", "aay"},
			{"net/minecraft/item/ItemAxe", "yl"},
			{"net/minecraft/item/Item", "zw"},
			{ "net/minecraft/item/ItemBlock", "yo" },
			{"net/minecraft/util/MovingObjectPosition$MovingObjectType", "auh$a"},
			{"net/minecraft/util/MovingObjectPosition", "auh"},
			{"net/minecraft/client/gui/inventory/GuiInventory", "azc"},
			{"net/minecraft/client/gui/GuiChat", "awv"},
			{"net/minecraft/entity/player/InventoryPlayer", "wm"},
			{"net/minecraft/item/ItemEnderPearl", "zk"},
			{"net/minecraft/client/renderer/entity/RenderEntityItem", "bjf"},
			{"net/minecraft/entity/item/EntityItem", "uz"},
			{ "net/minecraft/block/Block", "afh" },
			{ "net/minecraft/block/state/IBlockState", "alz" },
			{"net/minecraft/util/BlockPos", "cj"},
			{"net/minecraft/client/settings/GameSettings", "avh"},
			{ "net/minecraft/client/settings/KeyBinding", "avb" },
			{"net/minecraft/block/BlockAir", "aey"},
			{ "keyBindSprint", "ae" },
			{ "pressed", "h" },
			{ "pressTime", "i" },
			{"gameSettings", "t"},
			{"getTextureManager", "P"},
			{ "getBlockState", "p" },
			{ "getBlock", "c" },
			{ "getIdFromBlock", "a" },
			{"theMinecraft", "S"},
			{"thePlayer", "h"},
			{"theWorld", "f"},
			{"currentScreen", "m"},
			{"getRenderManager", "af"},
			{"getEntityRenderObject", "a"},
			{"doRenderEntity", "a"},
			{"mainModel", "f"},
			{"PROJECTION", "c"},
			{"MODELVIEW", "b"},
				{"getSlot", "a"},
			{"playerEntities", "j"},
			{ "getDisplayName", "f_" },
			{"getUnformattedTextForChat", "e"},
			{"getLocationSkin", "i"},
			{"getLocationSkinByName", "c"},
			{"rotationPitch", "z"},
			{ "jumpTicks", "bn" },
			{"rotationYaw", "y"},
			{"prevRotationYaw", "A"},
			{"prevRotationPitch", "B"},
			{"posX", "s"},
			{"posY", "t"},
			{"posZ", "u"},
			{"motionX", "v"},
			{"motionY", "w"},
			{"motionZ", "x"},
			{"maxHurtResistantTime", "aD"},
			{"hurtResistantTime", "Z"},
			{"hurtTime", "au"},
			{"bipedHeadwear", "f"},
			{"bipedRightArm", "h"},
			{"bipedLeftArm", "i"},
			{"bipedRightLeg", "j"},
			{"bipedLeftLeg", "k"},
			{"rotateAngleX","f"},
			{"rotateAngleY","g"},
			{"rotateAngleZ","h"},
			{"prevRenderYawOffset", "aJ"},
			{"renderYawOffset", "aI"},
			{"renderPartialTicks", "c"},
			{"lastTickPosX", "P"},
			{"lastTickPosY", "Q"},
			{"lastTickPosZ", "R"},
			{"timer", "Y"},
			{"net/minecraft/util/MovementInput", "beu"},
			{"movementInput", "b"},
			{"moveStrafeInput", "a"},
			{"moveForwardInput", "b"},
			{"jumpInput", "c"},
			{"sneakInput", "d"},
			{"keyBindForward", "Y"},
			{"keyBindBack", "aa"},
			{"keyBindLeft", "Z"},
			{"keyBindRight", "ab"},
			{"keyBindJump", "ac"},
			{"keyBindSprint", "ae"},
			{"keyBindSneak", "ad"},
			{"getDistanceToEntity", "g"},
			{"regeneration", "l"},
			{"isUsingItem", "bS"},
			{"swingItem", "bw"},
			{"getActivePotionEffect", "b"},
			{"potionID", "b"},
			{"getPotionID", "a"},
			{"getDuration", "b"},
			{"duration", "c"},
			{"potionId", "l"},
			{"getEntityItem", "l"},
			{"itemRenderer", "a"},
			{"doRender", "a"},
			{"displayWidth", "d"},
			{"displayHeight", "e"},
			{ "renderPosX", "o" },
			{ "renderPosY", "p" },
			{ "renderPosZ", "q" },
			{"drawRect", "a"},
			{"getStringWidth", "a"},
			{"drawString", "a"},
			{"fontRendererObj", "k"},
			{ "getHealth", "bn" },
			{ "getMaxHealth", "bu" },
			{"setAlwaysRenderNameTag",  "g"},
			{ "setInvisible", "e" },
			{ "isInvisible", "ax" },
			{"maxHurtResistantTime", "aD"},
			{"hurtResistantTime", "Z"},
			{ "viewerPosX", "h" },
			{ "viewerPosY", "i" },
			{ "viewerPosZ", "j" },
			{"boundingBox", "f"},
			{"minX", "a"},
			{"minY", "b"},
			{"minZ", "c"},
			{"maxX", "d"},
			{"maxY", "e"},
			{"maxZ", "f"},
			{"prevPosX", "p"},
			{"prevPosY", "q"},
			{"prevPosZ", "r"},
			{"isSneaking", "av"},
			{ "isSprinting", "aw" },
			{ "setSprinting", "d" },
			{"rotationYawHead", "aK"},
			{"onGround", "C"},
			{"getHeldItem", "bA"},
			{"item", "d"},
			{"getItem", "b"},
			{"typeOfHit", "a"},
			{"BLOCK", "b"},
			{"ENTITY", "c"},
			{ "objectMouseOver", "s" },
			{ "inWater", "Y" },
			{ "isInWeb", "H" },
			{ "moveForwardEntity", "ba" },
			{ "moveStrafingEntity", "aZ" },
			{ "timerSpeed", "d" },
			{ "inventory", "bi" },
			{ "currentItem", "c" },
			{ "getStackInSlot", "a" },
			{ "getStackDisplayName", "q" },
			{ "metadata", "f" },
			{"entityHit", "d"},
			{"getName", "e_"},
			{"getGameProfile", "cd"},
			{"getDisplayName", "f_"},
			{ "getDebugFPS", "ai"},
			{"setPosition", "b"},
			{"leftClickCounter", "ag"},
			{ "hurtResistantTime", "Z" },
			{ "isSwingInProgress", "ar" },
			{ "getCurrentArmor", "q" },
			{ "getMaxDamage", "j" },
			{ "getItemDamage", "h" },
			{ "dropOneItem", "a" },
			{ "keyBindUseItem", "ag" },
			{ "slotIn", "p_82169_1_" },
			{ "slotIn", "I" },
			{ "rightClickDelayTimer", "ap" },
			{ "blockHitDelay", "g" },
			{ "keyBindAttack", "ai" },
			{ "setKeyBindState", "a" },
			{ "onTick", "a" },
			{ "keyCode", "g" },
			{ "width", "J" },
			{ "height", "K" },
			{ "net/minecraft/scoreboard/Scoreboard", "auo" },
			{ "net/minecraft/scoreboard/Team", "auq" },
			{ "net/minecraft/scoreboard/ScorePlayerTeam", "aul" },
			{"net/minecraft/util/ResourceLocation", "jy"},
			{"net/minecraft/client/renderer/texture/TextureManager", "bmj"},
			{"net/minecraft/client/renderer/texture/ITextureObject", "bmk"},
			{"bindTexture", "a"},
			{"getTexture", "b"},
			{"getGlTextureId", "b"},
			{ "net/minecraft/client/renderer/entity/RenderItem", "bjh" },
			{ "net/minecraft/client/renderer/RenderHelper", "avc" },
			{ "getScoreboard", "Z" },
			{ "getPlayersTeam", "h" },
			{ "getColorPrefix", "e" },
			{ "getColorSuffix", "f" },
			{ "getRegisteredName", "b" },
			{ "isSameTeam", "a" },
			{ "renderItem", "ab" },
			{ "renderItemIntoGUI", "a" },
			{ "enableGUIStandardItemLighting", "c" },
			{ "disableStandardItemLighting", "a" },
			{ "net/minecraft/entity/player/EntityPlayer", "wn" },
			{ "net/minecraft/world/World", "adm" },
			{ "net/minecraft/client/multiplayer/WorldClient", "bdb" },
			{ "net/minecraft/scoreboard/ScoreObjective", "auk" },
			{ "net/minecraft/scoreboard/Score", "aum" },
			{ "getObjectiveInDisplaySlot", "a" },
			{ "getObjective", "b" },
			{ "getValueFromObjective", "c" },
			{ "getScorePoints", "c" },
			{ "getAbsorptionAmount", "bN" },
			{ "swingItem", "bw" },
			{ "clickMouse", "aw" },
			{ "swingProgressInt", "as" },
			{ "playerController", "c" },
			{ "windowClick", "a" },
			{ "inventoryContainer", "bj" },
			{ "windowId", "d" },
			{ "net/minecraft/item/ItemArmor", "yj" },
			{ "net/minecraft/item/ItemFood", "zs" },
			{ "net/minecraft/item/ItemAppleGold", "zt" },
			{ "net/minecraft/item/ItemEnderPearl", "zk" },
			{ "net/minecraft/potion/Potion", "pe" },
			{ "net/minecraft/potion/PotionEffect", "pf" },
			{ "potionTypes", "a" },
			{ "net/minecraft/entity/item/EntityItem", "uz" },
			{ "net/minecraft/client/renderer/entity/RenderEntityItem", "bjf" },
			{ "net/minecraft/inventory/Container", "xi" },
			{ "net/minecraft/inventory/Slot", "yg" },
			{ "getSlot", "a" },
			{ "getStack", "d" },
			{ "getMaxDamage", "j" },
			{ "getItemDamage", "h" },
			{ "armorType", "b" },
			{ "damageReduceAmount", "c" },
			{ "displayGuiScreen", "a" },
			{ "closeScreen", "n" },
			{ "updateController", "e" },
			{ "net/minecraft/network/play/client/C16PacketClientStatus", "ig" },
			{ "net/minecraft/network/play/client/C16PacketClientStatus$EnumState", "ig$a" },
			{ "OPEN_INVENTORY_ACHIEVEMENT", "c" },
			{ "PERFORM_RESPAWN", "a" },
			{ "net/minecraft/network/play/client/C0BPacketEntityAction", "is" },
			{ "net/minecraft/network/play/client/C0BPacketEntityAction$Action", "is$a" },
			{ "START_SPRINTING", "d" },
			{ "STOP_SPRINTING", "e" },
			{ "sendQueue", "a" },
			{ "addToSendQueue", "a" },
			{ "net/minecraft/client/network/NetHandlerPlayClient", "bcy" },
			{ "net/minecraft/network/Packet", "ff" },
			{ "net/minecraft/network/play/client/C03PacketPlayer", "ip" },
			{ "net/minecraft/network/play/client/C03PacketPlayer$C05PacketPlayerLook", "ip$c" },
			{ "yaw", "d" },
			{ "pitch", "e" },
			{ "rotating", "h" }
		};
		break;
	}
	case LUNAR_1_8: {
		g_Mappings = {
			{"net/minecraft/client/Minecraft", "net/minecraft/client/Minecraft"},
			{"net/minecraft/client/entity/AbstractClientPlayer", "net/minecraft/client/entity/AbstractClientPlayer"},
			{"net/minecraft/client/entity/EntityPlayerSP", "net/minecraft/client/entity/EntityPlayerSP"},
			{"net/minecraft/client/entity/EntityClientPlayerMP", "net/minecraft/client/entity/EntityPlayerSP"},
			{"net/minecraft/entity/EntityLivingBase", "net/minecraft/entity/EntityLivingBase"},
			{"net/minecraft/client/multiplayer/WorldClient", "net/minecraft/client/multiplayer/WorldClient"},
			{"net/minecraft/client/multiplayer/PlayerControllerMP", "net/minecraft/client/multiplayer/PlayerControllerMP"},
			{"net/minecraft/client/gui/GuiScreen", "net/minecraft/client/gui/GuiScreen"},
			{"net/minecraft/client/renderer/entity/RenderManager", "net/minecraft/client/renderer/entity/RenderManager"},
			{"net/minecraft/client/renderer/ActiveRenderInfo", "net/minecraft/client/renderer/ActiveRenderInfo"},
			{"net/minecraft/client/gui/inventory/GuiInventory", "net/minecraft/client/gui/inventory/GuiInventory"},
			{"net/minecraft/entity/Entity", "net/minecraft/entity/Entity"},
			{"net/minecraft/entity/player/EntityPlayer", "net/minecraft/entity/player/EntityPlayer"},
			{"net/minecraft/entity/player/InventoryPlayer", "net/minecraft/entity/player/InventoryPlayer"},
			{"net/minecraft/inventory/Container", "net/minecraft/inventory/Container"},
			{"net/minecraft/inventory/Slot", "net/minecraft/inventory/Slot"},
			{"net/minecraft/item/ItemStack", "net/minecraft/item/ItemStack"},
			{"net/minecraft/item/Item", "net/minecraft/item/Item"},
			{"net/minecraft/item/ItemArmor", "net/minecraft/item/ItemArmor"},
			{"net/minecraft/item/ItemFood", "net/minecraft/item/ItemFood"},
			{"net/minecraft/item/ItemAppleGold", "net/minecraft/item/ItemAppleGold"},
			{"net/minecraft/util/ResourceLocation", "net/minecraft/util/ResourceLocation"},
			{"net/minecraft/client/renderer/texture/TextureManager", "net/minecraft/client/renderer/texture/TextureManager"},
			{"net/minecraft/client/renderer/texture/ITextureObject", "net/minecraft/client/renderer/texture/ITextureObject"},
			{"net/minecraft/network/play/client/C16PacketClientStatus", "net/minecraft/network/play/client/C16PacketClientStatus"},
			{"net/minecraft/network/play/client/C16PacketClientStatus$EnumState", "net/minecraft/network/play/client/C16PacketClientStatus$EnumState"},
			{"net/minecraft/client/network/NetHandlerPlayClient", "net/minecraft/client/network/NetHandlerPlayClient"},
			{"net/minecraft/network/Packet", "net/minecraft/network/Packet"},
			{"net/minecraft/util/MovingObjectPosition", "net/minecraft/util/MovingObjectPosition"},
			{"net/minecraft/util/MovingObjectPosition$MovingObjectType", "net/minecraft/util/MovingObjectPosition$MovingObjectType"},
			{"net/minecraft/client/settings/GameSettings", "net/minecraft/client/settings/GameSettings"},
			{"net/minecraft/client/settings/KeyBinding", "net/minecraft/client/settings/KeyBinding"},
			{"net/minecraft/client/renderer/entity/RenderItem", "net/minecraft/client/renderer/entity/RenderItem"},
			{"net/minecraft/client/renderer/RenderHelper", "net/minecraft/client/renderer/RenderHelper"},
			{"net/minecraft/util/Timer", "net/minecraft/util/Timer"},
			{"net/minecraft/world/World", "net/minecraft/world/World"},
			{"net/minecraft/scoreboard/Scoreboard", "net/minecraft/scoreboard/Scoreboard"},
			{"net/minecraft/scoreboard/Team", "net/minecraft/scoreboard/Team"},
			{"net/minecraft/scoreboard/ScorePlayerTeam", "net/minecraft/scoreboard/ScorePlayerTeam"},
			{"net/minecraft/scoreboard/ScoreObjective", "net/minecraft/scoreboard/ScoreObjective"},
			{"net/minecraft/scoreboard/Score", "net/minecraft/scoreboard/Score"},
			{"net/minecraft/potion/Potion", "net/minecraft/potion/Potion"},
			{"net/minecraft/potion/PotionEffect", "net/minecraft/potion/PotionEffect"},
			{"net/minecraft/util/IChatComponent", "net/minecraft/util/IChatComponent"},
			{"theMinecraft", "theMinecraft"},
			{"thePlayer", "thePlayer"},
			{"theWorld", "theWorld"},
			{"currentScreen", "currentScreen"},
			{"gameSettings", "gameSettings"},
			{"objectMouseOver", "objectMouseOver"},
			{"playerController", "playerController"},
			{"renderItem", "renderItem"},
			{"getRenderManager", "getRenderManager"},
			{"timer", "timer"},
			{"leftClickCounter", "leftClickCounter"},
			{"rightClickDelayTimer", "rightClickDelayTimer"},
			{"blockHitDelay", "blockHitDelay"},
			{"playerEntities", "playerEntities"},
			{"getMaxHealth", "getMaxHealth"},
			{"getHealth", "getHealth"},
			{"getTextureManager", "getTextureManager"},
			{"getScoreboard", "getScoreboard"},
			{"getPlayersTeam", "getPlayersTeam"},
			{"getObjectiveInDisplaySlot", "getObjectiveInDisplaySlot"},
			{"getValueFromObjective", "getValueFromObjective"},
			{"getScorePoints", "getScorePoints"},
			{"getColorPrefix", "getColorPrefix"},
			{"getColorSuffix", "getColorSuffix"},
			{"getRegisteredName", "getRegisteredName"},
			{"isSameTeam", "isSameTeam"},
			{"PROJECTION", "PROJECTION"},
			{"MODELVIEW", "MODELVIEW"},
			{"getHeldItem", "getHeldItem"},
			{"isUsingItem", "isUsingItem"},
			{"getDisplayName", "getDisplayName"},
			{"getUnformattedTextForChat", "getUnformattedTextForChat"},
			{"getLocationSkin", "getLocationSkin"},
			{"getLocationSkinByName", "getLocationSkin"},
			{"bindTexture", "bindTexture"},
			{"getTexture", "getTexture"},
			{"getGlTextureId", "getGlTextureId"},
			{"getActivePotionEffect", "getActivePotionEffect"},
			{"jumpTicks", "jumpTicks"},
			{"rotationPitch", "rotationPitch"},
			{"rotationYaw", "rotationYaw"},
			{"prevRotationYaw", "prevRotationYaw"},
			{"prevRotationPitch", "prevRotationPitch"},
			{"posX", "posX"},
			{"posY", "posY"},
			{"posZ", "posZ"},
			{"lastTickPosX", "lastTickPosX"},
			{"lastTickPosY", "lastTickPosY"},
			{"lastTickPosZ", "lastTickPosZ"},
			{"motionX", "motionX"},
			{"motionY", "motionY"},
			{"motionZ", "motionZ"},
			{"onGround", "onGround"},
			{"hurtTime", "hurtTime"},
			{"hurtResistantTime", "hurtResistantTime"},
			{"maxHurtResistantTime", "maxHurtResistantTime"},
			{"swingProgressInt", "swingProgressInt"},
			{"getDistanceToEntity", "getDistanceToEntity"},
			{"isInvisible", "isInvisible"},
			{"setPosition", "setPosition"},
			{"typeOfHit", "typeOfHit"},
			{"BLOCK", "BLOCK"},
			{"ENTITY", "ENTITY"},
			{"entityHit", "entityHit"},
			{"getName", "getName"},
			{"getGameProfile", "getGameProfile"},
			{"inventory", "inventory"},
			{"inventoryContainer", "inventoryContainer"},
			{"currentItem", "currentItem"},
			{"keyBindUseItem", "keyBindUseItem"},
			{"setKeyBindState", "setKeyBindState"},
			{"displayGuiScreen", "displayGuiScreen"},
			{"onTick", "onTick"},
			{"keyCode", "keyCode"},
			{"windowClick", "windowClick"},
			{"windowId", "windowId"},
			{"getSlot", "getSlot"},
			{"getStack", "getStack"},
			{"item", "item"},
			{"metadata", "itemDamage"},
			{"getItem", "getItem"},
			{"getCurrentArmor", "getCurrentArmor"},
			{"getStackInSlot", "getStackInSlot"},
			{"getMaxDamage", "getMaxDamage"},
			{"getItemDamage", "getItemDamage"},
			{"armorType", "armorType"},
			{"damageReduceAmount", "damageReduceAmount"},
			{"sendUseItem", "sendUseItem"},
			{"sendQueue", "sendQueue"},
			{"addToSendQueue", "addToSendQueue"},
			{"updateController", "updateController"},
			{"renderItemIntoGUI", "renderItemIntoGUI"},
			{"enableGUIStandardItemLighting", "enableGUIStandardItemLighting"},
			{"disableStandardItemLighting", "disableStandardItemLighting"},
			{"regeneration", "regeneration"},
			{"potionTypes", "potionTypes"},
			{"duration", "duration"},
			{"getDuration", "getDuration"},
			{"setJumping", "setJumping"},
			{"width", "width"},
			{"height", "height"},
			{"renderPosX", "renderPosX"},
			{"renderPosY", "renderPosY"},
			{"renderPosZ", "renderPosZ"},
			{"renderPartialTicks", "renderPartialTicks"},
			{"net/minecraft/util/AxisAlignedBB", "net/minecraft/util/AxisAlignedBB"},
			{"boundingBox", "boundingBox"},
			{"minX", "field_72340_a"},
			{"minY", "field_72338_b"},
			{"minZ", "field_72339_c"},
			{"maxX", "field_72336_d"},
			{"maxY", "field_72337_e"},
			{"maxZ", "field_72334_f"}
		};
		break;
	}
	default:
		break;
	}
}

std::string Mapper::Get(const char* mapping, int type)
{
	auto it = g_Mappings.find(mapping);
	if (it == g_Mappings.end())
		return std::string("");

	std::string ret;
	switch (type)
	{
	case 1:
		ret = it->second;
		break;
	case 2:
		ret = "L" + it->second + ";";
		break;
	case 3:
		ret = "()L" + it->second + ";";
		break;
	default:
		ret = it->second;
		break;
	}

	return ret;
}
